server:
  port: 8500
  servlet:
    context-path: /
pagehelper:
  helper-dialect: mysql
  reasonable: "true"
  support-methods-arguments: "true"
  params: count=countSql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taotao
    username: root
    password: 123456
  resources:
    static-locations: classpath:/META-INF/resouces/,classpath:/resouces/
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    content-type: text/html
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/**/**.xml
